apiVersion: v1
data:
  db_host: {{ .Values.secrets.host }}
  db_name: {{ .Values.secrets.name }}
  db_password: {{ .Values.secrets.password }}
  db_port: {{ .Values.secrets.port }}
  db_username: {{ .Values.secrets.username }}
kind: Secret
metadata:
  name: database-secret
type: Opaque
