---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: autoscale-pvc-cronjob
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - command: ["python", "/app/autoscale-pvc.py"]
              env:
                - name: KUBECONFIG
                  value: /root/.kube/config
                - name: THRESHOLD_GIB
                  value: '80'
                - name: MAX_SIZE_GIB
                  value: '90'
              image: autoscale-pvc-cronjob:latest
              name: autoscale-pvc-container
            # You can add other environment variables if needed
          restartPolicy: OnFailure
  schedule: 0 0 * * 0