apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: csapi-app
  namespace: dev
spec:
  dnsNames:
    - dev.success4.us
    - auth.dev.success4.us
  secretName: csapi-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer