apiVersion: v1
kind: Service
metadata:
  name: {{ include "cs-kube.fullname" . }}
  labels:
    {{- include "cs-kube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: 7077
      targetPort: 7077
      protocol: TCP
      name: masterport
  selector:
    {{- include "cs-kube.selectorLabels" . | nindent 4 }}
