apiVersion: v1
kind: ConfigMap
metadata:
  name: control-center-configmap
data:
  CC_AUTH_USER: guest
  CC_PORT: "5000"
  CC_HOST: "0.0.0.0"
  # CC_JOB_STORE_URL: {{ .Values.configmap.cc_job_store_url }}
  CC_JOB_STORE_URL: {{ .Values.configmap.cc_job_store_url }}