apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-poc 
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: supports4@success4.us
    privateKeySecretRef:
      name: letsencrypt-poc-key
    solvers:
    - http01:
        ingress:
          class: nginx
