apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-serviceaccount
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["objectstorage.oraclecloud.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["identity"]
  resources: ["*"]
  verbs: ["*"]
