---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: psql-cronjob
spec:
  jobTemplate:
    metadata:
      name: psql-cronjob
    spec:
      template:
        spec:
          containers:
            - image: psql-cronjob:v1
              imagePullPolicy: IfNotPresent
              name: psql-cronjob
              resources: {}
          restartPolicy: OnFailure
  schedule: '*/5 * * * *'