{{- if (include "postgresql.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.auth.enablePostgresUser }}
  postgres-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "postgres-password" "providedValues" (list "global.postgresql.auth.postgresPassword" "auth.postgresPassword") "context" $) }}
  {{- end }}
  {{- if not (empty (include "postgresql.username" .)) }}
  host: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "host" "providedValues" (list "global.postgresql.auth.host" "auth.host") "context" $) }}
  name: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "name" "providedValues" (list "global.postgresql.auth.database" "auth.database") "context" $) }}
  username: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "username" "providedValues" (list "global.postgresql.auth.username" "auth.username") "context" $) }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "password" "providedValues" (list "global.postgresql.auth.password" "auth.password") "context" $) }}
  port: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "port" "providedValues" (list "global.postgresql.auth.port" "auth.port") "context" $) }}
  {{- end }}
  {{- if eq .Values.architecture "replication" }}
  replication-password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.names.fullname" .) "key" "replication-password" "providedValues" (list "auth.replicationPassword") "context" $) }}
  {{- end }}
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
  {{- if and .Values.ldap.enabled (or .Values.ldap.bind_password .Values.ldap.bindpw) }}
  ldap-password: {{ coalesce .Values.ldap.bind_password .Values.ldap.bindpw  | b64enc | quote }}
  {{- end }}
{{- end -}}
