apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: dev
spec:
  dnsNames:
    - dev.success4.us
  secretName: selfsigned-cert-tls
  issuerRef:
    name: dev-selfsigned
    