---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.ingress.tls.secretName }}
spec:
  acme:
    privateKeySecretRef:
      name: {{ .Values.ingress.tls.secretName }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
spec:
  commonName: {{ .Values.ingress.hosts.host }}
  dnsNames:
    - {{ .Values.ingress.hosts.host }}
    - {{ .Values.ingress.hosts.authhost }}
  issuerRef:
    kind: Issuer
    name: {{ .Values.ingress.tls.secretName }}
  secretName: {{ .Values.ingress.tls.certificateName }}